### ISSUE TITLE
Link table fails on NaN

### ISSUE THREAD

**Issue by HaydenSansum** [RobinL/fuzzymatcher#27]
The link table function will fail and throw a Type error if there are any NaNs in the matching columns.

 ```TypeError: ('sequence item 0: expected str instance, float found', 'occurred at index 10')```

**Comment by RobinL** [comment]
code to fix is here https://github.com/RobinL/fuzzymatcher/blob/800d0de35188410d81e537a281b2b89a050b397e/fuzzymatcher/data_preprocessor_default.py#L53
