### ISSUE TITLE
Don't depend on python-levenstein

### ISSUE THREAD

**Issue by RobinL** [RobinL/fuzzymatcher#40]
See here - https://stackoverflow.com/a/47629587/1779128

**Comment by modesitt-sesco** [comment]
This is now a problem on the python3.7.4 install from apt-get as well. Was forced to build from source to not get a gcc error.

**Comment by RobinL** [comment]
Thanks.  I think solution is probably to follow fuzzywuzzy and make `python-Levenstein` an optional dependency, falling back on difflib see:

The only function I use from `python-Levenstein` is `ratio`
https://github.com/seatgeek/fuzzywuzzy/blob/df5b67a32d7ddaf2e86fe1247b6ff7e3b57e0805/fuzzywuzzy/fuzz.py#L9

**Comment by RobinL** [comment]
Working on a PR here: #48
